# Set the permalink structure for blog posts.
permalink: pretty

# Basic website configuration.
url: https://helpd.me
markdown: kramdown
highlighter: pygments

# Set the defaults for posts and pages.
layout: default
tagline: Helpd.me

# Plugins
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
