# Set the permalink structure for blog posts.
permalink: /blog/:categories/:title

# Basid website configuration.
url: https://helpd.me

# Set the defaults for posts and pages.
layout: default
tagline: Helpd.me
